import { Schema as S } from "effect";
import {
  DaemonCloudState,
  DaemonIntegrationKind,
  DaemonProviderConnection,
} from "./daemon";

// ─── Device state — the daemon's live, manifest-derived snapshot ─────
//
// The daemon is the source of truth for what's on the box. This snapshot is
// read LIVE through the relay and never persisted cloud-side: a dashboard with
// no live daemon socket shows offline, which is the truth. Its `items` shape is
// GENERATED by walking the registry manifest (`packages/registry/manifest.ts`),
// so adding/removing a registry item is reflected with NO daemon release — the
// daemon computes each item's installed-or-not by running that item's own
// `install.sh -s` (the same probe that decides a command's `done`/`not_done`).
// See `docs/proposals/daemon-owned-state-stateless-relay.md`.

export type {
  TDaemonCloudState,
  TDaemonIntegrationKind,
  TDaemonProviderConnection,
} from "./daemon";
// Re-export the pieces device-state composes so the contract imports from one
// module.
export {
  DaemonCloudState,
  DaemonIntegrationKind,
  DaemonProviderConnection,
} from "./daemon";

/**
 * One registry item's live state on this box, as reported by `install.sh -s`.
 * `area`+`slug` identify it in the registry manifest; `installed` is the
 * measured fact; `version` is reported when the probe can read it.
 */
export const ItemState = S.Struct({
  area: DaemonIntegrationKind,
  slug: S.String,
  installed: S.Boolean,
  version: S.optional(S.NullOr(S.String)),
  detail: S.optional(S.String),
});
export type TItemState = S.Schema.Type<typeof ItemState>;

/**
 * The full device snapshot — daemon self + subscription providers + every
 * registry item's live state. Supersedes `DaemonStatus`: `connections` keeps the
 * per-provider shape; `integrations` (a hand-rolled, daemon-hardcoded list) is
 * replaced by `items`, generated from the registry manifest.
 */
export const DeviceState = S.Struct({
  daemon_version: S.String,
  /** Whether an sk-llm key is set (the daemon installs keyless). */
  key_configured: S.Boolean,
  /** Auto-update opt-in (default on). Absent on daemons too old to report it. */
  auto_update: S.optional(S.Boolean),
  /** Result of the last cloud bootstrap — drives the 3-state Providers UI. */
  cloud_state: DaemonCloudState,
  /** The OS-sandbox posture this daemon booted with. */
  sandbox: S.optional(S.Literal("enforced", "off", "unsupported", "error")),
  /** Loopback port for this daemon's `/v1/*` + `/whoami` surface. */
  port: S.optional(S.Number),
  /** This daemon's X25519 public key (SPKI DER, base64) for cross-machine seal. */
  pubkey: S.optional(S.String),
  /** Subscription-provider connections (claude_code/chatgpt/kimi_code). */
  connections: S.Array(DaemonProviderConnection),
  /** Registry items' live state — generated by walking the registry manifest. */
  items: S.Array(ItemState),
});
export type TDeviceState = S.Schema.Type<typeof DeviceState>;

// ─── New relay → watcher frame (stateless-relay transport) ───────────
//
// Supersedes the old `status_push` + `presence` frames: presence is encoded by
// `online`, the snapshot by `device_state` (present iff online). Defined
// additively; the full `RelayFrame` union swap happens with the Phase 3 relay
// rewrite.

/** relay → watcher. A key's daemon presence and/or device-state changed.
 *  `online:false` is the offline flip (the relay holds no socket for the key);
 *  `device_state` is present iff `online:true`. */
export const RelayDeviceStateFrame = S.Struct({
  type: S.Literal("device_state"),
  key_id: S.String,
  online: S.Boolean,
  device_state: S.optional(DeviceState),
});
export type TRelayDeviceStateFrame = S.Schema.Type<
  typeof RelayDeviceStateFrame
>;
